### ISSUE TITLE
Fixing the href

### ISSUE THREAD

**Issue by akshitadixit** [GDSC-IIIT-Kalyani/hacktober-leaderboard#16]
On [this](https://secret-inlet-87050.herokuapp.com/projects) page, the navbar links do not work due to flask url.

**Comment by RajMhatre20** [comment]
I would like to work on this

**Comment by akshitadixit** [comment]
Sure

**Comment by Anmol376OP** [comment]
I would like to work on this

**Comment by RajMhatre20** [comment]
How can I start the app on my local machine?

**Comment by akshitadixit** [comment]
@RajMhatre20 follwo the following steps to start the app:
`git clone <repo-link>`
`cd <repo-folder>`
`pip install flask, pygithub`
`python app.py`

Then wait for a few minutes, this should take a minimum of 2 minutes by the clock to get started and you should see a link on the terminal/cmd, click on it to view. Sorry about the lack of a README, the issue is being worked upon.

**Comment by RajMhatre20** [comment]
I did what you said it threw a bunch of errors
```
Traceback (most recent call last):
  File "C:\Users\rajmh\Desktop\tp\hacktober-leaderboard\app.py", line 55, in <module>
    func()
  File "C:\Users\rajmh\Desktop\tp\hacktober-leaderboard\app.py", line 24, in func
    for repo in repos:
  File "C:\Users\rajmh\AppData\Roaming\Python\Python39\site-packages\github\PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "C:\Users\rajmh\AppData\Roaming\Python\Python39\site-packages\github\PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "C:\Users\rajmh\AppData\Roaming\Python\Python39\site-packages\github\PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "C:\Users\rajmh\AppData\Roaming\Python\Python39\site-packages\github\Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "C:\Users\rajmh\AppData\Roaming\Python\Python39\site-packages\github\Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by akshitadixit** [comment]
@RajMhatre20 oh, you also need to create a github personal access token by going into the developer settings on github. Replace that with the token on line 19 in app.py

This is required since we're using Github API for the same.

**Comment by RajMhatre20** [comment]
I'm not able to set up the project, I created GitHub personal access token, replaced it, even then it is showing me the same error. I think it's better if someone else looks after this issue. Sorry for inconvience

**Comment by akshitadixit** [comment]
@Anmol376OP importance of having a README
